version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
      - "8443:443"
    volumes:
      - files:/files
    hostname: requestbox
    domainname: localhost
    environment:
      HOSTNAME: "3.6.226.68"
      MIX_ENV: docker
      DATABASE_URL: postgres://requestbox:okchanged@db/requestbox
      SECRET_KEY_BASE: bbe5c9bc68b1f64ffd82bd852c96bf631dfbb77e50a67aadb235774381c21104e0b499b1d21afacd6b9ee5a9ebc28a1d30269cae307a0e22fd6bbcff4389e4fd
      REQUESTBOX_SSL_KEY_PATH: "/app/priv/"
      REQUESTBOX_SSL_CERT_PATH: "/app/priv/"
  db:
    image: postgres:alpine
    volumes:
      - database:/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: requestbox
      POSTGRES_USER: requestbox
      POSTGRES_PASSWORD: okchanged
      PGDATA: /database
    restart: on-failure:10
volumes:
  database:
    driver: local
  files:
    driver: local
